import { test, expect } from '@playwright/test'

test('theme follows system live and preserves explicit overrides across reloads and tabs', async ({ page, context }) => {
  await page.goto('/')
  const select = page.getByRole('button', { name: /当前主题/ })
  const html = page.locator('html')
  await expect(select).toHaveAttribute('data-appearance', 'auto')
  await page.emulateMedia({ colorScheme: 'dark' })
  await expect(html).toHaveClass(/dark/)
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(html).not.toHaveClass(/dark/)
  await select.click()
  await page.emulateMedia({ colorScheme: 'dark' })
  await expect(html).not.toHaveClass(/dark/)
  await page.reload()
  await expect(select).toHaveAttribute('data-appearance', 'light')
  await expect(html).not.toHaveClass(/dark/)
  await select.click()
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(html).toHaveClass(/dark/)
  const other = await context.newPage()
  await other.goto('/blog')
  await expect(other.locator('html')).toHaveClass(/dark/)
  await select.click()
  await expect(html).not.toHaveClass(/dark/)
  await expect(other.getByRole('button', { name: /当前主题/ })).toHaveAttribute('data-appearance', 'auto')
  await expect(other.locator('html')).not.toHaveClass(/dark/)
  await page.reload()
  await expect(select).toHaveAttribute('data-appearance', 'auto')
  await page.emulateMedia({ colorScheme: 'dark' })
  await expect(html).toHaveClass(/dark/)
})
